[code-quality]
linters = ["pylint", "black", "isort"]
[tool.isort]
profile = "black"
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
[tool.mllint.testing]
report = "tests-report.xml"
[tool.mllint.testing.coverage]
report = "coverage.xml"
targets = { line = 80.0 } 
[tool.mllint.rules]
disabled = ["version-control/data/dvc-has-remote", "version-control/data/dvc-has-files", "code-quality/bandit/no-issues"]